In [1]:
import json
import urllib.request
import pandas as pd
import os
import glob
import cv2
import numpy as np
import matplotlib.pyplot as plt

ImportError: No module named 'cv2'

In [6]:
hoge = pd.DataFrame({'city': ['kagawa', 'ehime', 'tokushima', 'kouchi'], 'no': [1, 2, 3, 4]})

In [7]:
hoge

city  no
0     kagawa   1
1      ehime   2
2  tokushima   3
3     kouchi   4

In [11]:
city_df = hoge
flg_df = ['kagawa', 'ehime']
flg_l = []
for city in city_df['city']:
    if city in flg_df:
        flg_l.append(1)
    else:
        flg_l.append(0)
city_df['flg'] = flg_l

In [12]:
city_df

city  no  flg
0     kagawa   1    1
1      ehime   2    1
2  tokushima   3    0
3     kouchi   4    0

In [19]:
def load_image(img_dir='../imgs/'):
    """
    Load image and label data
    @ param img_dir: directory pass for image folder
    @ return img_l: numpay array of image
    @ return lbl_l: numpay array of label
    """
    img_names = os.listdir(img_dir)[0:3]
    img_l = []
    lbl_l = []
    for img_name in img_names:
        lbl_l.append(int(img_name[0]))
        print(img_name[0])
        img = cv2.imread(str(img_dir + img_name))
        b,g,r = cv2.split(img)
        img = cv2.merge([r,g,b])
        img_l.append(img)
    
    img_l = np.array(img_l)
    lbl_l = np.array(lbl_l)
    return img_l, lbl_l

In [20]:
img_l, lbl_l = load_image()

['0_Kasaoka_Okayama.jpg', '0_Tarumizu_Kagoshima.jpg', '1_Kitakyushu_Fukuoka.jpg']
0
0
1
[[[[ 31  49  35]
   [ 31  49  35]
   [ 31  49  31]
   ..., 
   [ 39  52  35]
   [ 35  50  31]
   [ 35  50  31]]

  [[ 31  49  35]
   [ 31  49  31]
   [ 27  45  27]
   ..., 
   [ 35  50  31]
   [ 35  50  31]
   [ 35  50  31]]

  [[ 35  52  35]
   [ 35  52  39]
   [ 31  49  31]
   ..., 
   [ 31  49  31]
   [ 35  50  31]
   [ 31  49  31]]

  ..., 
  [[123 119 107]
   [119 111  99]
   [117 109  92]
   ..., 
   [ 12  17  12]
   [ 12  17  12]
   [ 12  17  12]]

  [[127 119 111]
   [117 109  92]
   [111 103  91]
   ..., 
   [ 12  17  12]
   [ 17  21  16]
   [ 16  19  14]]

  [[132 124 117]
   [123 119 107]
   [117 109  92]
   ..., 
   [ 16  19  14]
   [ 17  21  16]
   [ 17  21  16]]]


 [[[ 28  35  38]
   [ 28  35  38]
   [ 28  35  38]
   ..., 
   [ 28  35  38]
   [ 28  35  38]
   [ 28  35  38]]

  [[ 28  35  38]
   [ 28  35  38]
   [ 28  35  38]
   ..., 
   [ 37  33  35]
   [ 28  35  38]
   [ 35  34  26]]

(array([[[[ 31,  49,  35],
          [ 31,  49,  35],
          [ 31,  49,  31],
          ..., 
          [ 39,  52,  35],
          [ 35,  50,  31],
          [ 35,  50,  31]],
 
         [[ 31,  49,  35],
          [ 31,  49,  31],
          [ 27,  45,  27],
          ..., 
          [ 35,  50,  31],
          [ 35,  50,  31],
          [ 35,  50,  31]],
 
         [[ 35,  52,  35],
          [ 35,  52,  39],
          [ 31,  49,  31],
          ..., 
          [ 31,  49,  31],
          [ 35,  50,  31],
          [ 31,  49,  31]],
 
         ..., 
         [[123, 119, 107],
          [119, 111,  99],
          [117, 109,  92],
          ..., 
          [ 12,  17,  12],
          [ 12,  17,  12],
          [ 12,  17,  12]],
 
         [[127, 119, 111],
          [117, 109,  92],
          [111, 103,  91],
          ..., 
          [ 12,  17,  12],
          [ 17,  21,  16],
          [ 16,  19,  14]],
 
         [[132, 124, 117],
          [123, 119, 107],
          [117, 109,  92],

In [21]:
data_set = np.load('./hoge.npz')
X = data_set["x"]
Y = data_set["y"]

In [22]:
X

array([[[[ 0.12109375,  0.19140625,  0.13671875],
         [ 0.12109375,  0.19140625,  0.13671875],
         [ 0.12109375,  0.19140625,  0.12109375],
         ..., 
         [ 0.15234375,  0.203125  ,  0.13671875],
         [ 0.13671875,  0.1953125 ,  0.12109375],
         [ 0.13671875,  0.1953125 ,  0.12109375]],

        [[ 0.12109375,  0.19140625,  0.13671875],
         [ 0.12109375,  0.19140625,  0.12109375],
         [ 0.10546875,  0.17578125,  0.10546875],
         ..., 
         [ 0.13671875,  0.1953125 ,  0.12109375],
         [ 0.13671875,  0.1953125 ,  0.12109375],
         [ 0.13671875,  0.1953125 ,  0.12109375]],

        [[ 0.13671875,  0.203125  ,  0.13671875],
         [ 0.13671875,  0.203125  ,  0.15234375],
         [ 0.12109375,  0.19140625,  0.12109375],
         ..., 
         [ 0.12109375,  0.19140625,  0.12109375],
         [ 0.13671875,  0.1953125 ,  0.12109375],
         [ 0.12109375,  0.19140625,  0.12109375]],

        ..., 
        [[ 0.48046875,  0.46484375,